# Generated by Django 6.0.4 on 2026-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmodel',
            name='stoken',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
